




# # megatest reaper utility
# $(PREFIX)/bin/.$(ARCHSTR)/lib/ducttape-lib.so: ducttape-lib.scm inteldate.scm mimetypes.scm
# 	csc -s ducttape-lib.scm -j ducttape-lib -o ducttape-lib.so
# 	$(INSTALL) ducttape-lib.so $@

# $(PREFIX)/bin/mtest-reaper: $(PREFIX)/bin/.$(ARCHSTR)/lib/ducttape-lib.so mtest-reaper.scm
# 	csc mtest-reaper.scm 
# 	$(INSTALL) mtest-reaper $@


