perl -pi -e 's/dbr:dbstruct-set-strdb/dbr:dbstruct-strdb-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-stime/dbr:dbstruct-stime-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-rundb-path/dbr:dbstruct-set-rupath-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-rundb/dbr:dbstruct-rundb-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-run-id/dbr:dbstruct-run-id-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-rtime/dbr:dbstruct-rtime-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-refdb/dbr:dbstruct-refdb-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-path/dbr:dbstruct-path-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-olddb/dbr:dbstruct-olddb-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-mtime/dbr:dbstruct-mtime-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-main-path/dbr:dbstruct-main-path-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-main/dbr:dbstruct-main-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-locdbs/dbr:dbstruct-locdbs-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-localdb/dbr:dbstruct-localdb-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-local/dbr:dbstruct-local-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-inuse/dbr:dbstruct-inuse-set/g' *.scm
perl -pi -e 's/dbr:dbstruct-set-inmem/dbr:dbstruct-inmem-set/g' *.scm

perl -pi -e 's/dbr:dbstruct-get-strdb/dbr:dbstruct-strdb/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-stime/dbr:dbstruct-stime/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-runrec/dbr:dbstruct-runrec/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-rundb-path/dbr:dbstruct-rundb-path/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-rundb/dbr:dbstruct-rundb/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-run-id/dbr:dbstruct-run-id/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-rtime/dbr:dbstruct-rtime/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-refdb/dbr:dbstruct-refdb/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-path/dbr:dbstruct-path/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-olddb/dbr:dbstruct-olddb/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-mtime/dbr:dbstruct-mtime/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-main-path/dbr:dbstruct-main-path/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-main/dbr:dbstruct-main/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-locdbs/dbr:dbstruct-locdbs/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-localdb/dbr:dbstruct-localdb/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-local/dbr:dbstruct-local/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-inuse/dbr:dbstruct-inuse/g' *.scm
perl -pi -e 's/dbr:dbstruct-get-inmem/dbr:dbstruct-inmem/g' *.scm
