
all : launch-many queuefeeder queuefeeder-server

launch-many : launch-many.scm
	csc launch-many.scm

queuefeeder : queuefeeder.scm
	csc queuefeeder.scm

queuefeeder-server : queuefeeder-server.scm
	csc queuefeeder-server.scm
