#!/bin/bash

prefix=$1
cmd=$2

if [ "$LD_LIBRARY_PATH" != "" ];then
  echo "INFO: Using LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >&2
  echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
else
  echo "INFO: LD_LIBRARY_PATH not set" >&2
fi

echo "#!/bin/bash"
echo "source $prefix/bin/.\$(lsb_release -sr)/cfg.sh"
echo "exec $prefix/bin/.\$(lsb_release -sr)/$cmd \"\$@\""

